CREATE TABLE PAISES 
(
  ID_PAIS NUMBER 
, NOMBRE VARCHAR2(64) NOT NULL 
, CONTINENTE VARCHAR2(24) NOT NULL 
, CAPITAL VARCHAR2(64) NOT NULL 
, SITUACION VARCHAR2(128) 
, NOTAS VARCHAR2(128) 
, CONSTRAINT PAISES_PK PRIMARY KEY 
  (
    ID_PAIS 
  )
  ENABLE 
);


--------------------------------------------------------
-- Archivo creado  - lunes-octubre-19-2020   
--------------------------------------------------------
REM INSERTING into GIISGBD401.PAISES
SET DEFINE OFF;
Insert into GIISGBD401.PAISES (ID_PAIS,NOMBRE,CONTINENTE,CAPITAL,SITUACION,NOTAS) values ('1','España','Europa','Madrid',null,null);
Insert into GIISGBD401.PAISES (ID_PAIS,NOMBRE,CONTINENTE,CAPITAL,SITUACION,NOTAS) values ('2','Francia','Europa','París',null,null);
Insert into GIISGBD401.PAISES (ID_PAIS,NOMBRE,CONTINENTE,CAPITAL,SITUACION,NOTAS) values ('3','Estados Unidos','América','Washington',null,null);
Insert into GIISGBD401.PAISES (ID_PAIS,NOMBRE,CONTINENTE,CAPITAL,SITUACION,NOTAS) values ('4','México','América','Ciudad de México',null,null);
Insert into GIISGBD401.PAISES (ID_PAIS,NOMBRE,CONTINENTE,CAPITAL,SITUACION,NOTAS) values ('6','China','Asia','Pekín',null,null);
Insert into GIISGBD401.PAISES (ID_PAIS,NOMBRE,CONTINENTE,CAPITAL,SITUACION,NOTAS) values ('7','Rusia','Asia','Moscú',null,null);
Insert into GIISGBD401.PAISES (ID_PAIS,NOMBRE,CONTINENTE,CAPITAL,SITUACION,NOTAS) values ('5','Alemania','Europa','Berlín',null,null);
Insert into GIISGBD401.PAISES (ID_PAIS,NOMBRE,CONTINENTE,CAPITAL,SITUACION,NOTAS) values ('8','Italia','Europa','Roma',null,null);
Insert into GIISGBD401.PAISES (ID_PAIS,NOMBRE,CONTINENTE,CAPITAL,SITUACION,NOTAS) values ('9','Portugal','Europa','Lisboa',null,null);
Insert into GIISGBD401.PAISES (ID_PAIS,NOMBRE,CONTINENTE,CAPITAL,SITUACION,NOTAS) values ('10','Australia','Oceanía','Canberra',null,null);

CREATE TABLE RIOS 
(
  ID_RIO NUMBER 
, NOMBRE VARCHAR2(100) NOT NULL 
, LONGITUD NUMBER 
, CUENCA NUMBER 
, CAUDAL_MEDIO NUMBER 
, NACIMIENTO VARCHAR2(64) NOT NULL 
, PAIS_NACIMIENTO NUMBER NOT NULL
, DESEMBOCADURA VARCHAR2(64) NOT NULL 
, PAIS_DESEMBOC NUMBER NOT NULL 
, CONSTRAINT RIOS_PK PRIMARY KEY 
  (
    ID_RIO 
  )
  ENABLE 
);



ALTER TABLE RIOS
ADD CONSTRAINT RIOS_FK_DESEMBOC FOREIGN KEY
(
  PAIS_DESEMBOC 
)
REFERENCES PAISES
(
  ID_PAIS 
)
ENABLE;

ALTER TABLE RIOS
ADD CONSTRAINT RIOS_FK_NACIMIENTO FOREIGN KEY
(
  PAIS_NACIMIENTO
)
REFERENCES PAISES
(
  ID_PAIS 
)
ENABLE;



--------------------------------------------------------
-- Archivo creado  - lunes-octubre-19-2020   
--------------------------------------------------------
REM INSERTING into GIISGBD401.RIOS
SET DEFINE OFF;
Insert into GIISGBD401.RIOS (ID_RIO,NOMBRE,LONGITUD,CUENCA,CAUDAL_MEDIO,NACIMIENTO,PAIS_NACIMIENTO,DESEMBOCADURA,PAIS_DESEMBOC) values ('1','Turia','280','6393,6','14','Guadalaviar','1','Mar Mediterráneo','1');
Insert into GIISGBD401.RIOS (ID_RIO,NOMBRE,LONGITUD,CUENCA,CAUDAL_MEDIO,NACIMIENTO,PAIS_NACIMIENTO,DESEMBOCADURA,PAIS_DESEMBOC) values ('2','Garona','568,9','55000','700','Circo de Saboredo','1','Estuario de la Gironda','2');
Insert into GIISGBD401.RIOS (ID_RIO,NOMBRE,LONGITUD,CUENCA,CAUDAL_MEDIO,NACIMIENTO,PAIS_NACIMIENTO,DESEMBOCADURA,PAIS_DESEMBOC) values ('3','Colorado','2333','629100','620','Montañas Rocosas','3','Golfo de California','4');
Insert into GIISGBD401.RIOS (ID_RIO,NOMBRE,LONGITUD,CUENCA,CAUDAL_MEDIO,NACIMIENTO,PAIS_NACIMIENTO,DESEMBOCADURA,PAIS_DESEMBOC) values ('4','Sacramento','719','70000','665','Confluencia de los ríos Sacramento Sur y Sacramento Medio','3','Bahía Suisun','3');
Insert into GIISGBD401.RIOS (ID_RIO,NOMBRE,LONGITUD,CUENCA,CAUDAL_MEDIO,NACIMIENTO,PAIS_NACIMIENTO,DESEMBOCADURA,PAIS_DESEMBOC) values ('5','Bravo','3034','607965','160','Montañas San Juan de Colorado','3','Golfo de México','4');
Insert into GIISGBD401.RIOS (ID_RIO,NOMBRE,LONGITUD,CUENCA,CAUDAL_MEDIO,NACIMIENTO,PAIS_NACIMIENTO,DESEMBOCADURA,PAIS_DESEMBOC) values ('8','Danubio','2888','817000','6500','Selva Negra','5','Mar Negro','5');
Insert into GIISGBD401.RIOS (ID_RIO,NOMBRE,LONGITUD,CUENCA,CAUDAL_MEDIO,NACIMIENTO,PAIS_NACIMIENTO,DESEMBOCADURA,PAIS_DESEMBOC) values ('6','Murray','2375','1061469','450','Alpes Australianos','10','Océano Índico','10');
Insert into GIISGBD401.RIOS (ID_RIO,NOMBRE,LONGITUD,CUENCA,CAUDAL_MEDIO,NACIMIENTO,PAIS_NACIMIENTO,DESEMBOCADURA,PAIS_DESEMBOC) values ('7','Yangtsé','6300','1800000','31900','Meseta tibetana','6','Mar de la China Oriental','6');
