CREATE TABLE CAMBIOLOG
(
  TABLA VARCHAR2(20) 
, COLUMN2 DATE 
, COLUMN3 VARCHAR2(20) 
);


ALTER TABLE CAMBIOLOG  
MODIFY (TABLA NOT NULL);

ALTER TABLE CAMBIOLOG  
MODIFY (FECHA NOT NULL);

ALTER TABLE CAMBIOLOG  
MODIFY (ACCIÓN NOT NULL);

ALTER TABLE CAMBIOLOG
ADD CONSTRAINT CAMBIOLOG_PK PRIMARY KEY 
(
  FECHA 
, TABLA 
, ACCIÓN 
)
ENABLE;




CREATE OR REPLACE TRIGGER LOG_PAISES
BEFORE DELETE OR INSERT OR UPDATE ON PAISES FOR EACH ROW
DECLARE n_rows INTEGER;
BEGIN

    SELECT COUNT(*) INTO n_rows FROM CAMBIOLOG;

    IF(n_rows >= 10) THEN
        DELETE FROM CAMBIOLOG WHERE FECHA = (SELECT MIN(FECHA) FROM CAMBIOLOG);
    END IF;

    IF INSERTING THEN        
        INSERT INTO CAMBIOLOG VALUES ('PAISES', SYSDATE, 'INSERTAR');
    END IF;
    
    IF UPDATING THEN
        INSERT INTO CAMBIOLOG VALUES ('PAISES', SYSDATE, 'ACTUALIZAR ' || :NEW.ID_PAIS);
    END IF;
    
    IF DELETING THEN
        INSERT INTO CAMBIOLOG VALUES ('PAISES', SYSDATE, 'BORRAR ' || :OLD.ID_PAIS);
    END IF;
    
END;



create or replace TRIGGER LOG_RIOS 
BEFORE DELETE OR INSERT OR UPDATE ON RIOS FOR EACH ROW
DECLARE n_rows INTEGER;
BEGIN

    SELECT COUNT(*) INTO n_rows FROM CAMBIOLOG;

    IF(n_rows >= 10) THEN
        DELETE FROM CAMBIOLOG WHERE FECHA = (SELECT MIN(FECHA) FROM CAMBIOLOG);
    END IF;

    IF INSERTING THEN        
        INSERT INTO CAMBIOLOG VALUES ('RIOS', SYSDATE, 'INSERTAR');
    END IF;
    
    IF UPDATING THEN
        INSERT INTO CAMBIOLOG VALUES ('RIOS', SYSDATE, 'ACTUALIZAR ' || :NEW.ID_RIO);
    END IF;
    
    IF DELETING THEN
        INSERT INTO CAMBIOLOG VALUES ('RIOS', SYSDATE, 'BORRAR ' || :OLD.ID_RIO);
    END IF;
    
END;