 ---------------------------Práctica 4---------------------------

--EJERCICIO 3
--Transacción #3.1 -B

--READ COMMITED

SET TRANSACTION ISOLATION LEVEL READ COMMITTED NAME 'Sesion B';

--Cambio de sesión

SELECT COUNT(*) FROM DEPT; --Devuelve 6

--Cambio de sesión

SELECT COUNT(*) FROM DEPT; --Devuelve 7
COMMIT;
SELECT COUNT(*) FROM DEPT; --Devuelve 7

--SERIALIZABLE

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE NAME 'Sesion B';

--Cambio de sesión

SELECT COUNT(*) FROM DEPT; --Devuelve 6

--Cambio de sesión

SELECT COUNT(*) FROM DEPT; --Devuelve 6
COMMIT;
SELECT COUNT(*) FROM DEPT; --Devuelve 7

--Transacción #3.2 -B

--READ COMMITED

SET TRANSACTION ISOLATION LEVEL READ COMMITTED NAME 'Sesion B';

SELECT * FROM DEPT WHERE DEPTNO=151; --DEVUELVE 151, ADVERTISING, VLC

--Cambio de sesión

SELECT * FROM DEPT WHERE DEPTNO=151; --DEVUELVE 151, NEWNAME, VLC
COMMIT;
SELECT * FROM DEPT WHERE DEPTNO=151; --DEVUELVE 151, NEWNAME, VLC

--SERIALIZABLE

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE NAME 'Sesion B';

SELECT * FROM DEPT WHERE DEPTNO=151; --DEVUELVE 151, ADVERTISING, VLC

--Cambio de sesión

SELECT * FROM DEPT WHERE DEPTNO=151; --DEVUELVE 151, ADVERTISING, VLC
COMMIT;
SELECT * FROM DEPT WHERE DEPTNO=151; --DEVUELVE 151, NEWNAME, VLC

